# This name is also shown in the status badge.
name: Build Shopkeepers

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
  # Rebuild periodically to keep the cache alive:
  schedule:
  - cron: '45 4 * * 0,3'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/*.gradle*', '**/libs.versions.toml', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-m2
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/libs.versions.toml', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle
    - name: Cache Jabba JDK installations
      uses: actions/cache@v4
      with:
        path: ~/.jabba
        key: ${{ runner.os }}-jabba-${{ hashFiles('**/*.sh') }}
        restore-keys: |
          ${{ runner.os }}-jabba
    - name: Build Shopkeepers
      run: ./build.sh
    - name: Stage artifacts for upload
      run: mkdir staging && cp build/*.jar staging
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: staging
